- backend/graphql/schema.graphql
#97 introduced a regression into the graphql schema file.  (multiple root types aren't allowed).  This PR merges the two into a single root type.
> fix: merge migrations in graphql schema

- backend/graphql/schema.graphql
- backend/tests/Feature/UserPermissionsTest.php
This PR extends the GraphQL endpoint with user roles.
> feat: extend graphql with user roles

- backend/app/Exceptions/ClientException.php
- backend/app/GraphQL/Mutations/VerifyEmail.php
- backend/app/Models/User.php
- backend/app/Providers/AuthServiceProvider.php
- backend/config/mail.php
- backend/graphql/schema.graphql
- backend/tests/Feature/VerifyEmailTest.php
Does what it says on the tin.  Probably the best way to validate this PR is to check the unit tests.
To confirm the email notification is working:
- `lando extras enable mailhog`
- `lando rebuild -y`
- `lando start` (if needed)
- Visit https://ccr.lndo.site/register and create a new account
- Visit https://mailhog.ccr.lndo.site/ and see that the email was sent.
**Note: This is only the backend functionality.  Visiting the link contained in the email will not do anything at the moment**
I'm just breaking #87 into multiple PR's to keep them a little more reviewable.
> feat: implement email verification backend

- docs/package.json
- docs/yarn.lock
Sorry, I missed that docs had the elliptic package in it as well.
Upgrade docs dependencies.
Includes upgrades to address https://github.com/advisories/GHSA-r9p9-mrjm-926w
> fix(docs,deps): upgrade dependencies to address cve-2020-28498

- client/yarn.lock
- docs/yarn.lock
The PR addresses vulnerabilities with outdated versions in the dependency graph [reported by GitHub Dependabot](https://github.com/MESH-Research/CCR/security/dependabot):
* /docs/yarn.lock => ssri 
* /docs/yarn.lock => is-svg
* /client/yarn.lock => ssri
* /client/yarn.lock => is-svg
Closes Issue #188
> build: Upgrade Yarn Dependencies

- .gitignore
- backend/app/Models/User.php
- backend/composer.json
- backend/composer.lock
- backend/config/app.php
- backend/config/scout.php
- backend/graphql/schema.graphql
- backend/tests/Feature/UserQueryTest.php
- client/src/graphql/queries.js
- client/src/pages/Admin/UsersIndex.jest.spec.js
- client/src/pages/Admin/UsersIndex.vue
This extends the GraphQL API to search for users by various search terms.
Closes #175 
Example GraphQL Playground query:
```graphql
query SearchUsers {
userSearch(term:"abcdef", first: 10, page: 1) {
data {
id	
name
email
username
}
}
}
```
Edit: changed the name of the function argument from 'search' to 'term'
> feat: Add user search to GraphQL API

- backend/app/Models/Publication.php
- backend/app/Models/Role.php
- backend/app/Models/Submission.php
- backend/app/Models/User.php
- backend/database/factories/SubmissionFactory.php
- backend/database/migrations/2021_06_01_195428_create_submissions_table.php
- backend/database/migrations/2021_06_01_195428_create_submissions_tables.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/PublicationSeeder.php
- backend/database/seeders/SubmissionSeeder.php
- backend/graphql/publication.graphql
- backend/graphql/schema.graphql
- backend/graphql/submission.graphql
- backend/graphql/user.graphql
- backend/tests/Feature/SubmissionTest.php
- client/test/cypress/integration/admin/publications.spec.js
This PR:
* Introduces the `Submission` model
* Establishes a one-to-many relationship between submissions and publications
* Establishes a many-to-many relationship between submissions and users
* Updates the GraphQL endpoint for submissions
* submission - get a submission by ID
* submissions - get all submissions
* user.submissions - get all submissions for a user
* publication.submissions - get all submissions for a publication
* Adds seeding for publications and submissions
> feat: Add Submissions

- client/package.json
- client/yarn.lock
Reverts MESH-Research/CCR#388
one of the Publications unit tests is failing. 
```
• Tests\Feature\PublicationTest > publications have a many to many relationship with users
Failed asserting that 5 is equal to 4 or is less than 4.
at tests/Feature/PublicationTest.php:260
256▕                 );
257▕             });
258▕         });
259▕         User::all()->map(function ($user) use ($publication_count) {
➜ 260▕             $this->assertLessThanOrEqual($publication_count, $user->publications->count());
261▕             $user->publications->map(function ($publication) {
262▕                 $this->assertIsInt(
263▕                     Publication::where(
264▕                         'id',
1   [internal]:0
```
> revert: Revert "build(deps-dev): bump eslint-plugin-vue from 7.12.1 to 7.13.0 in /client"

- .lando.extras.yml
- client/src/css/app.sass
- client/test/cypress/plugins/index.js
This PR disables animations during cypress tests using the prefers-reduced-motion media query.  As a side effect this also causes the application to respect prefers-reduced-motion in general.
> test(client): disable animations during tests

- .github/workflows/test-e2e.yml
- .lando.extras.yml
- client/package.json
- client/quasar.extensions.json
- client/yarn.lock
- docs/contributing/testing.md
Upgrade cypress to the latest version and rearrange tooling so that cypress is installed as a dev yarn dependency.
Advantages:
- Latest version
- Cypress version is managed in the package.json, not in random .lando files.
- Smaller Docker image for Lando to D/l and build
- Easier to run cypress outside of docker and use the GUI (just run `yarn cypress open` in the client directory)
Caveats:
- After a lando rebuild, one will need to run `lando cypress install` to install the cypress binaries.
- **If you currently have cypress enabled in lando extras, disable and reenable it to pull in the new config**
> test(cypress): Upgrade cypress

- client/src/pages/Submissions.vue
- client/test/cypress/integration/submissions.spec.js
This PR 
* Makes the Submissions Cypress spec conform to ESLint standards
* Adds an assertion to the Submissions Cypress spec to ensure that the currently logged in user is assigned as the submitter by default upon creating a new submission.
- The work to make this default assignment was completed inadvertently in issue #491.
Closes Issue #501
> feat: Test that current user is the default submitter

- backend/tests/Feature/SubmissionTest.php
This PR addresses resolving an integrity constraint error that is occasionally produced in the the many-to-many relationship assertion in `SubmissionTest.php`.
Closes #679
> test: Increase reliability of SubmissionTest

- backend/app/Notifications/SubmissionCreation.php
- backend/database/migrations/2021_11_03_174907_create_notifications_table.php
- backend/tests/Feature/NotificationTest.php
This PR:
- Adds a new sample `SubmissionCreation` notification class 
- Adds a migration for the notifications table 
- Adds PHPUnit tests to assert that new functionality works 
Closes #685
> feat: Prepare Backend for Database Notifications

- backend/graphql/notification.graphql
- backend/graphql/schema.graphql
- backend/graphql/user.graphql
- backend/tests/Feature/NotificationTest.php
This PR:
* Adds the Notifications type to the GraphQL schema
* Adds a `notifications` property to the `User` type in GraphQL comprised of all the user's notifications
- This will only return data for the currently authenticated users
- The notification data can be optionally paginated
Closes #717
> feat: Add Notifications to GraphQL Endpoint

- .github/workflows/test-e2e.yml
This PR addresses the "Update Available!" warnings that appear whenever Lando runs a task within a GitHub Action. This also resolves the "unsupported version of DOCKER COMPOSE" warnings as well.
Old Logs:
New Logs:
> feat: Update Lando Version in GitHub Action

- backend/app/Events/SubmissionCreated.php
- backend/app/Listeners/EmailUsersAboutCreatedSubmission.php
- backend/app/Listeners/NotifyUsersAboutCreatedSubmission.php
- backend/app/Notifications/SubmissionCreated.php
- backend/app/Providers/EventServiceProvider.php
- backend/graphql/schema.graphql
- backend/tests/Feature/Notifications/SubmissionCreatedTest.php
- client/src/components/molecules/NotificationPopup.vue
- client/test/cypress/integration/submissions.spec.js
This PR:
* Adds functionality for sending an email and in-app notification to users upon the creation of a submission. Those users are:
- The submitter of the submission
- Any editor of the publication associated with the submission
* Adds Cypress and PHPUnit testing to ensure correct behavior
Closes #746
> feat: Populate Notification Data Upon Submission Creation

- backend/app/Models/Submission.php
- backend/database/factories/SubmissionFactory.php
- backend/database/migrations/2022_01_13_184123_add_submission_statuses.php
- backend/graphql/submission.graphql
- backend/tests/Feature/SubmissionTest.php
This PR:
* Adds `status` and `status_name` properties to the submissions model
* Adds a migration for the new column in the submissions table
* Bonus: Fixes an emergent bug with ordering (again somehow!) in the `testCreateSubmissionUserViaMutationAsAReviewCoordinator()` method of `SubmissionTest.php`
Closes #755
> feat: Add Submission Statuses

- client/src/graphql/fragments.js
- client/src/graphql/queries.js
- client/src/pages/Admin/Publications.jest.spec.js
- client/src/pages/Admin/UsersIndex.jest.spec.js
- client/src/pages/Publications.jest.spec.js
- client/src/pages/Submissions.jest.spec.js
- client/src/use/pagination.jest.spec.js
This PR: 
* add unit tests for pagination composable
* creates graphql fragment for pagination fields
* Implements fragment for existing queries
* Add type names to existing mocked paginated queries
> test(client): add tests for pagination composable

- client/src/components/atoms/VQInput.jest.spec.js
- client/src/components/atoms/VQInput.vue
- client/src/components/forms/AccountProfileForm.jest.spec.js
- client/src/components/forms/AccountProfileForm.vue
- client/src/components/forms/NewPasswordInput.vue
- client/src/components/forms/ProfileMetadataForm.jest.spec.js
- client/src/components/forms/ProfileMetadataForm.vue
- client/src/components/forms/VNewPasswordInput.vue
- client/src/components/forms/atoms/AccountProfileForm.vue
- client/src/components/forms/atoms/NewPasswordInputMeter.vue
- client/src/i18n/en-US/index.js
- client/src/pages/Account/MetadataPage.jest.spec.js
- client/src/pages/Account/ProfilePage.jest.spec.js
- client/src/pages/Account/ProfilePage.vue
- client/src/use/forms.jest.spec.js
- client/src/use/forms.js
- client/src/use/userValidation.jest.spec.js
- client/src/use/userValidation.js
This PR: 
* Adds a VQwrap form composable for validator are input reuse
* Adds VNewPasswordInput which is validator aware
* Factors out account profile form to its own page
* Uses userValidation composable to validation profile edit fields.
> fix(client): add client side validation to account profile edit page

- backend/database/seeders/SubmissionSeeder.php
- backend/tests/Feature/Notifications/SubmissionCreatedTest.php
This PR replaces hardcoded references to role IDs with constants as defined in `/backend/app/Models/Role.php`. 
Remarkably, there weren't nearly as many hardcoded references in `/backend` as I previously believed there were. 
Closes #643
> refactor: Replace string IDs with constants

- client/package.json
- client/src/components/atoms/SubmissionContent.vue
- client/yarn.lock
This PR converts the statically mocked HTML into Tiptap content presented with Tiptap's Highlight extension.
Closes #979
> refactor: Use Tiptap to Display Submission Text

- client/src/layouts/MainLayout.vue
This PR removes the `v-ripple` directive that's been [recently discovered to cause breaking changes in Quasar/vue 3.2.33](https://github.com/quasarframework/quasar/issues/13154).
> fix: Remove (newly) breaking v-ripple directive

- client/package.json
- client/yarn.lock
Per https://github.com/quasarframework/quasar/releases/tag/%40quasar%2Fapp-v3.4.0
Quasar switched from using @quasar/app to @quasar/app-webpack for the application dep.  This PR upgrades to that new package and resolves an outstanding vuln.
> build(deps,client): switch/upgrade to new @quasar/app-webpack package

- client/test/cypress/integration/account.spec.js
- client/test/cypress/integration/admin/publication_details.spec.js
- client/test/cypress/integration/admin/publications.spec.js
- client/test/cypress/integration/admin/user_details.spec.js
- client/test/cypress/integration/admin/users.spec.js
- client/test/cypress/integration/dashboard.spec.js
- client/test/cypress/integration/home.spec.js
- client/test/cypress/integration/login.spec.js
- client/test/cypress/integration/publications.spec.js
- client/test/cypress/integration/register.spec.js
- client/test/cypress/integration/submissiondetails.spec.js
- client/test/cypress/integration/submissionreview.spec.js
- client/test/cypress/integration/submissions.spec.js
- client/test/cypress/plugins/index.js
- client/test/cypress/support/helpers.js
Updates cypress axe errors from this: 
to this:
> test(client): add error logging to cypress axe errors

- client/src/components/forms/FindUserSelect.vue
- client/test/cypress/integration/admin/publication_details.spec.js
- client/test/cypress/integration/submissiondetails.spec.js
- client/test/cypress/integration/submissions.spec.js
Updates find user select to work around graphql/apollo locking up on quick queries. Bypasses the update mechanism from quasar to instead reactively update the query variables and call refetch on the original query which allows vueapollo to cancel duplicate queries on its own.
Once this gets merged it *should* clear up the two apollo dependabot PRs chillin in the open list.
Closes #1056.
> fix(client): Fix lockup in find-user-select component

- backend/app/GraphQL/Mutations/Login.php
- backend/app/GraphQL/Mutations/Logout.php
This PR fixes a warning on `Logout.php` encountered when rebuilding: 
```
Class App\Graphql\Mutations\Logout located in ./app/GraphQL/Mutations/Logout.php does not comply with psr-4 autoloading standard. Skipping.
```
Before:
After:
Bonus: this PR also removes some extra whitespace in `Login.php`
> fix: Namespace Discrepancy in Logout.php

- client/src/components/dialogs/BypassStyleCriteriaDialog.vue
- docs/index.md
This PR fixes the wrapping and alignment issue between the dialog text and icon in `BypassStyleCriteriaDialog.vue`
I discovered the [previous PR that was open for this](https://github.com/MESH-Research/CCR/pull/1132) was accidentally closed after I had renamed the branch. Lesson: rename branches before opening pull requests.
> fix: Alignment in Bypass Style Criteria Dialog

- backend/database/factories/StyleCriteriaFactory.php
- backend/database/seeders/StyleCriteriasSeeder.php
- backend/tests/Feature/StyleCriteriaTest.php
This PR:
* Uses the current unordered list content available on [PPJ's website](https://publicphilosophyjournal.org/instructions-for-reviewers/) for the seeded style criteria
* Makes style criteria factories embed sample style criteria descriptions in a `<p>` tag
* Adds some useful test cases to `StyleCriteriasTest` for protecting against XSS and ensuring that `<a>` tags are allowed 
Closes #1128
> feat: Use HTML in Style Criteria Seeder and Factory

- backend/database/factories/StyleCriteriaFactory.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/InlineCommentSeeder.php
- backend/database/seeders/OverallCommentSeeder.php
- backend/database/seeders/PublicationSeeder.php
- backend/database/seeders/StyleCriteriasSeeder.php
- backend/database/seeders/SubmissionFileSeeder.php
- backend/database/seeders/SubmissionSeeder.php
- backend/database/seeders/UserSeeder.php
This PR makes each seeder perform independently by moving the creation of models inside the seeder classes and calling them from the database seeder (the default seeder called when none is specified).  Seeders now also use callOnce to call the models they are dependent on. This means that a seeder can be called on its own and will seed only the data needed for that seeder to complete.
> refactor(api): move seeder calls into seeder classes

- backend/database/migrations/2021_06_01_195428_create_submissions_tables.php
- backend/database/migrations/2022_02_14_202738_create_settings_table.php
* Adds a missing down method for the `settings` table so that it can be removed properly when running a migration reset (`lando artisan migrate:reset`)
* Fixes a typo on a reference to the `submission_user` table so that it also gets removed properly when running a migration reset
Closes #1138
> fix(api): add missing method preventing migration:reset from succeeding

- .github/dependabot.yml
Updates dependabot config to use fix: for dependencies that are user facing (changes that could/should trigger a version bump if released)
> ci(dependabot): change non-dev updates to bugfix category

- client/src/graphql/queries.js
- client/src/i18n/en-US/index.js
- client/src/pages/SubmissionDetails.vue
This PR adds Quasar components to the Submission Details page for displaying an i18n-translated status label based on the database-derived status of the viewed submission.
Closes #1254
> feat: Add submission status to the submission details page

- docs/contributing/README.md
This pull request adds instructions for migrating and seeding the database, which resolves a missing part of the documentation that would help a developer unfamiliar with the application understand how they can log in to the application on the client. 
Closes #1276
> docs: Add migration and seeding instructions

- docs/guide/README.md
This pull request adds the introduction to the Guide page as drafted by Shelby Brewster and Stephanie Vasko with some modifications as agreed upon by the development team:
* Replaces occurrences of 'Pilcrow' with 'CCR'
* Removes the reference to a specific grant number
* Adds a link to a page on PPJ's website
Closes #1055
> docs: Add introduction to the Guide page of the documentation site

- .github/workflows/deploy.yml
- backend/Dockerfile
- client/.docker/default.conf.template
- docker-compose.yaml
Add script to deploy staging environment and adjust some issues with docker configuration.
* Test environment will be available at https://staging.ccrproject.dev
* Development seeders and migrate:fresh are run whenever master is updated.
* See [UserSeeder](https://github.com/MESH-Research/CCR/blob/master/backend/database/seeders/UserSeeder.php) for usernames and passwords available for login.
* All outgoing email is captured and redirected to https://mailhog.ccrproject.dev
closes #1332
> build: update configuration for staging deployment

- client/src/components/atoms/SubmissionContent.vue
- client/src/components/forms/CommentEditor.vue
- client/src/graphql/mutations.js
This updates the client to use the new expected input format for style criteria (an array of IDs) that are submitted on submissions. It also removes a `console.log()` statement.
> fix(client): Update client for new expected input format

- backend/Dockerfile
Fixes a missing library in the build for the php container preventing the build from successfully completing.
> build: fix missing library in staging build

- client/src/components/atoms/InlineCommentReply.vue
- client/src/components/atoms/OverallCommentReply.vue
Fixes warning generated during a client build: `[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.`
> fix(client): update deep selectors in comment reply quotes (deprecation)

- client/test/cypress/plugins/index.js
Fixes the following error message that appears when running cypress at the command line.
> test: fix error message about incorrect args

- client/src/pages/SubmissionsPage.vue
This fixes the dialog form that appears when submitting a submission for review on the Submissions page so that the correct language appears.
Closes #1730
> fix: Fix submitting a submission for review on the Submissions page

- client/src/components/forms/CommentEditor.vue
This makes cancel buttons appear for both inline and overall comments when a user is modifying them.
Closes #1616
> fix: Make cancel button appear when modifying comments

- backend/app/Models/User.php
- client/src/pages/VerifyEmail.vue
This pull request simplifies the searchable array used by TNTSearch so that only the most essential data is used for tokenization to prevent disruptions. It also adds an `await` keyword to the client template to address cases where current user data may not be available at the same time the email verification page has mounted.
Closes #1673
> fix: Fix email verification

- backend/composer.json
- backend/composer.lock
Update backend composer dependency to require php less than 8.2. A few deps currently don't support version 8.2 and it causes problems with renovate doing its thang.
> chore(deps): restrict php version to less than 8.2

- client/src/components/AppHeader.vue
- client/src/components/SubmissionTable.vue
- client/src/components/SubmissionTableActions.vue
- client/src/components/SubmissionTitle.vue
- client/src/components/atoms/SubmissionContent.vue
- client/src/graphql/queries.js
- client/src/i18n/en-US.json
- client/src/pages/ReviewsPage.jest.spec.js
- client/src/pages/ReviewsPage.vue
- client/src/pages/SubmissionsPage.vue
- client/src/router/routes.js
* Adds a new "Reviews" page
* Shows a list of reviews for the authenticated user
* as a reviewer
* as a coordinator
* Adds a new tab to the navigational bar, which now requires icons in the navigational bar to be hidden on extremely small viewports
* Refactors the action menu that appears on the Submissions page into a new component, `SubmissionTableActions`, so that it can be reused on the Reviews page and throughout the application
* Adds a `SubmissionTable` component
**Bonus**
* Automatically loads submission title renaming activity to the Activity section on the Submission Details page without requiring the user to refresh the page
* Fixes the potential for pilcrow numbering to overlap with submission content on the Submission Review page
Closes #1754
> feat: Add the Reviews page

- client/src/components/atoms/VQInput.vue
- client/src/components/forms/StyleCriteriaForm.vue
- updates the VQinput component to check for translation keys before displaying
Closes #1807
> fix: update component to check for existing translation key

- backend/database/seeders/UxSeeder.php
This PR creates a seeder for creating UX testing users/content/etc.  
Users 1-6: (Replace 1 with the number desired, passwords are all the same) 
tester1@pilcrow.dev
pilcrowRocks!@#
Submissions (Replace 1 with the number desired, each has the corresponding testing user as a reviewer): 
UX Test 1 Submission
For reviewer: 
After starting up pilcrow run
`lando artisan migrate:fresh --seed` to run the standard migrations
`lando artisan db:seed UxSeeder` to run the UX migrations
Note: this seeder will only run when manually run from the command line, a feat the staging build server will handle.
> feat: add ux testing seeder

- .github/workflows/container-build.yml
This PR adds a conditional to the publishing of container images to help prevent build errors on pull requests.
> chore: do not publish docker images on pull requests or rennovate action

- .lando/install-pandoc.sh
Updates the pandoc installation script to install the correct architecture of pandoc on M1 Macs.
> chore(lando): check for architecture when installing pandoc

- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- client/src/apollo/apollo-router-guards.vitest.spec.js
- docs/contributing/README.md
Introduced by the markdownlint upgrade, I didn't catch this before merging.
> docs(style): fix Bare URL markdownlint violation

- client/yarn.lock
This reverts commit 921a31507ccbf43df7c2fc9ebc14fcd28ec6a6b1.
A bug exists in graphql 16.7.1 that causes an error when quasar is running in development mode.   This doesn't affect the build or the compiled assets so it missed detection during the automated testing.  
Ref: https://github.com/graphql/graphql-js/issues/3925
> fix: downgrade dependency graphql/graphql-js to 16.6.0

- .lando.yml
Docker image has been upgraded to php 8.2 without issue and tests are now running from inside the built containers, so lando's version should ideally match the container version for good DX.
> chore(lando): upgrade lando appserver to php 8.2

- client/test/cypress/support/index.js
This fixes a leftover line of debugging code that I forgot to remove from this commit: https://github.com/MESH-Research/Pilcrow/commit/20df267bcf69eaf8452651c797b38bcf09ffbb64#diff-1bf643980de446a3dd3732c24adafec075efd3ad9e0f80ad4e203b2a55ed5974
This code was partially reverted in this commit: https://github.com/MESH-Research/Pilcrow/commit/0571672b0f36d34ff56af60f9c467b4c63b39d5a
> fix: Revert debugging code

- .gitignore
- backend/app/Policies/SubmissionPolicy.php
- backend/app/Rules/SubmissionIsReviewable.php
- backend/graphql/submission.comments.graphql
- backend/tests/Api/SubmissionCommentTest.php
- backend/tests/TestCase.php
This prevents new inline and overall comment creation mutations from being ran on the backend for submissions whose status is not "Under Review".
Bonus:
* Adds files generated from `php artisan lighthouse:ide-helper` to `.gitignore`
* Read more: https://lighthouse-php.com/6/testing/phpunit.html#assertions
* Fixes the `unsetJsonTrace` method in `backend/tests/TestCase.php`
Closes #1791
> feat: Add backend protection from newly added comments for submissions out of review

- client/package.json
- client/yarn.lock
Fix for graphql/graphql issue causing compilation to fail.
***Note:*** Developers will need to run `yarn install` in the `/client` directory.
> fix(client): override vite version to fix graphql/graphql issue

- client/src/components/dialogs/SelectIconDialog.vue
- client/src/components/molecules/FormActions.vue
* Fixes the icon picker on the publication config page for choosing the icon of style criteria
Bonus:
* Fixes a contrast issue for the "saving" button that briefly appears after choosing to save an icon for a style criteria
Closes #1835
> fix: Restore icon picker functionality

- client/src/i18n/en-US.json
- client/src/pages/Publication/PublicationHomePage.vue
- client/src/pages/SubmissionsPage.vue
* Changes the text for the "Submit a Work" buttons so that they read "Submit New Submission" instead
* Adds some whitespace above those buttons
* Changes the page title that reads "Submit a Work" to "Create Submission"
Closes #1914
> refactor: Change submit buttons

- client/src/components/AppHeader.vue
- client/src/components/forms/AccountProfileForm.vue
- client/src/i18n/en-US.json
- client/src/layouts/Account/AccountLayout.vue
- client/src/pages/DashboardPage.vue
- client/test/cypress/integration/header.cy.js
* Changes "Account Info" to "Login and Password"
* Changes "Profile Info" to "Profile"
* Removes "My Account" from main dropdown menu and adds "Profile" and "Login and Password" as dropdown menu options
* Makes icon usage consistent for these options
* Flips the order of these options so that Profile is first
Closes #1929
> feat: Improve inconsistent menu and naming

- client/src/components/SubmissionTableActions.vue
- client/src/components/atoms/SubmissionToolbar.vue
- client/src/graphql/queries.js
- client/src/use/guiElements.js
- client/src/use/user.js
- client/test/cypress/integration/reviewspage.cy.js
- client/test/cypress/integration/submissionreview.cy.js
This pull request 
* Hides the "Status Options" button on the Review page for reviewers
* Hides the "Change Status" option within submission table action menus for reviewers 
Closes #1916 
> [!NOTE]
> I discovered faulty behavior as far as status changing and [reported it here](https://app.zenhub.com/workspaces/pilcrow-development-5ff39ba363391e0019713c87/issues/gh/mesh-research/pilcrow/1916#issuecomment-1702876080).
> feat: Hide status changing from reviewers

- backend/database/factories/PublicationFactory.php
- client/src/pages/Publication/PublicationHomePage.vue
This changes the placeholder text on seeded publication home pages and create submission pages so that it is no longer lorem ipsum but plain English describing what the text represents. 
Closes #1915
> feat: Change default content for publication home pages and create submission pages

- client/src/css/app.sass
- client/src/pages/SubmissionsPage.vue
- darkens the background color on tooltips
- updates the contrast on tooltips to pass WCAG AAA guidelines with a 10.86:1 contrast ratio
Closes #1909
> style: update tooltip background

- client/src/pages/Publication/Setup/UsersPage.vue
This fixes a reference to the `i18n.js` file in Publication Setup > Users for publications that have no administrators . 
Closes #1966
> fix: Reference to translated string

- pilcrow.code-workspace
Remove color theming from the recently-added VSCode Workspace file
> refactor: Remove color theming from VSCode Workspace file

- backend/app/GraphQL/Validators/ProfileMetadataValidator.php
- backend/graphql/profile_metadata.graphql
- backend/graphql/schema.graphql
- backend/tests/Api/UserQueryTest.php
- client/src/components/forms/ProfileMetadataForm.vitest.spec.js
- client/src/components/forms/ProfileMetadataForm.vue
- client/src/css/app.sass
- client/src/graphql/fragments.js
- client/src/i18n/en-US.json
- client/src/pages/Account/ProfilePage.vitest.spec.js
- client/src/use/profileMetadata.js
- client/test/cypress/integration/profile.cy.js
Drops keywords from the user interface. (The field isn't used anywhere and can be added back in once we figure out how we'll make use of it.
> feat: drop keywords field from UI

- client/src/apollo/apollo-links.js
This PR (should) fix the issue with random refreshes during page navigations.  The cause *seems* to be that when the CSRF cookie is fetched, the response is a `204 No Content`.  Because we don't expect there to be content, we also don't read the body of the response.   Chrome apparently sees this as an error (https://stackoverflow.com/a/67276787/407726).  
Reproduction was sporadic however, so I'm not completely convinced this was/is the actual issue just yet.
> fix: eliminate random page refreshes on navigation

- backend/app/GraphQL/Mutations/DeleteInlineComment.php
- backend/app/GraphQL/Mutations/DeleteOverallComment.php
- backend/app/Models/InlineComment.php
- backend/app/Models/OverallComment.php
- backend/app/Policies/SubmissionPolicy.php
- backend/app/Rules/InlineCommentIdValidity.php
- backend/app/Rules/OverallCommentIdValidity.php
- backend/database/migrations/2023_12_18_213126_add_softdeletes_to_inline_comments.php
- backend/database/migrations/2023_12_18_213319_add_softdeletes_to_overall_comments.php
- backend/database/seeders/InlineCommentSeeder.php
- backend/database/seeders/OverallCommentSeeder.php
- backend/graphql/submission.comments.graphql
- backend/graphql/submission.graphql
- backend/tests/Api/SubmissionCommentTest.php
- client/src/components/atoms/CommentActions.vue
- client/src/components/atoms/CommentHeader.vue
- client/src/components/atoms/InlineComment.vue
- client/src/components/atoms/OverallComment.vue
- client/src/components/atoms/SubmissionCommentSection.vitest.spec.js
- client/src/components/atoms/SubmissionCommentSection.vue
- client/src/components/atoms/SubmissionContent.vue
- client/src/components/dialogs/ConfirmCommentDeletion.vue
- client/src/components/molecules/InlineComments.vitest.spec.js
- client/src/components/molecules/InlineComments.vue
- client/src/graphql/fragments.js
- client/src/graphql/mutations.js
- client/src/graphql/queries.js
- client/src/i18n/en-US.json
- client/test/cypress/integration/admin/publication_setup.cy.js
- client/test/cypress/integration/submissionreview.cy.js
* Adds functionality for deleting overall and inline comments and their replies by their authors
* Comments are soft deleted so that they can be recovered by a system administrator if necessary
* Extends the `replies` attribute of inline and overall comment replies to include their own replies 
* Extends `SubmissionPolicy` to ensure that only the authors of comments can delete them
* Ensures that sensitive data of soft deleted comments are transformed when accessed by the client. This includes
* `username` becomes `""`
* `content` becomes `"This comment has been deleted"`
* `style_criteria` becomes `[]`
* Updates various queries of comments throughout to include soft deleted comments
* Enables soft deleting on the `inline_comments` and `overall_comments` tables
* Fixes …
> feat: Add comment deletion

- client/src/css/app.sass
- Fixes a color contrast issue on the inline comment heading when a comment is highlighted
Closes #2056
> fix: Fix Contrast Issue on Active Comment Menu

- client/src/components/SubmissionTitle.vue
- client/src/components/atoms/EmailVerificationSendButton.vue
- client/src/components/dialogs/ConfirmCommentDeletion.vue
- client/src/components/dialogs/ConfirmStatusChangeDialog.vue
- client/src/components/dialogs/ReinviteUserDialog.vue
- client/src/i18n/en-US.json
This refactors usages of the `notify` library to use the `useFeedbackMessages` composable that's located in `guiElements.js`. This makes the presentation of these notifications consistent across the app.
Bonus: This also adds some missing submission status change messages for deletions and archives. 
Closes #1804
> refactor: Use composable for notify messages

- client/src/components/atoms/CommentHeader.vue
- client/src/components/atoms/InlineComment.vue
- client/src/components/atoms/InlineCommentReference.vue
- client/src/components/atoms/SubmissionContent.vue
- client/src/i18n/en-US.json
- client/src/pages/SubmissionReview.vue
This adds a "reference" button to inline comment headers. This enables bidirectional scrolling behavior in that both the inline comments panel and the submission content area will scroll to make sure both the annotation and inline comment are visible whenever an inline comment's annotation or reference is clicked. Previously, this scrolling only happened within the inline comments panel when an annotation was clicked. Now, when an inline comment's reference is clicked, the corresponding annotation within the submission content area is scrolled to as well. 
Closes #1936
> feat: Bidirectional Inline Comment Navigation

- client/src/components/forms/CommentEditor.vue
This resolves a check annotation on GitHub for pull requests wherein it complains that the attribute "ref" should go before ":editor" in CommentEditor.vue.
> fix: Move component attribute

- client/src/components/atoms/InlineComment.vue
- client/src/components/atoms/OverallComment.vue
- client/src/components/atoms/SubmissionCommentSection.vitest.spec.js
- client/src/components/forms/CommentEditor.vue
- client/src/components/molecules/InlineComments.vitest.spec.js
- client/src/i18n/en-US.json
- client/src/pages/SubmissionsPage.vitest.spec.js
* Adds to the "Show/Hide Replies" buttons a count of how many replies a comment thread contains. 
* Bonus
* Prevents the "Cancel" button from appearing for the overall comment draft form at the bottom of the Submission Review page. Note: this button still appears for the draft form for overall comment replies.
* Adds a missing property to `SubmissionsPage.vitest.spec.js`
Closes #2070
> feat: Add reply counts to threads

- client/src/components/SubmissionTableActions.vue
- client/src/components/atoms/StatusChangeDropdown.vue
- client/src/components/atoms/SubmissionPreviewToolbar.vue
- client/src/components/atoms/SubmissionToolbar.vue
- client/src/components/atoms/SubmissionViewToolbar.vue
- client/src/components/dialogs/ConfirmStatusChangeDialog.vue
- client/src/i18n/en-US.json
- client/src/pages/SubmissionDraft.vue
- client/src/use/guiElements.js
- client/test/cypress/integration/notificationpopup.cy.js
- client/test/cypress/integration/submissionreview.cy.js
* Refactors status changing template logic to a new component `StatusChangeDropdown`
* uses data-driven logic for improved reusability
* Simplifies submission acceptance process
* Accepting for review is no longer necessary; only opening for review
* Adds the `StatusChangeDropdown` component to the preview, view, and review pages
* Adds a check for status changes to draft and initially submitted submissions so that the interface changes accordingly
* Draft submissions are redirected from the preview page to the view page
* Initially Submitted submissions are redirected from the view page to the review page
* Bonus: Adds scope attributes to `i18n` tags to prevent warnings about global scope
Closes #2078
> feat: Submit Submission from Preview Page

- .github/actions/build-image/action.yaml
- .github/workflows/CI.yml
- docker-bake.hcl
To make it slightly easier to get the frontend bundle when priming a CDN, we zip up the bundle from the build process and attach to the web container image as a related artifact.
This pull request introduces updates to the Docker image build process and CI workflow for Pilcrow. Key changes include enhancements to the `.github/actions/build-image` action, modifications to the CI workflow to support token usage, and updates to the `docker-bake.hcl` file to enable local output for web builds.
* [`.github/actions/build-image/action.yaml`](diffhunk://#diff-7360bea25001af0257834160753c7ae85cf9677376c4f19212a700635021fe90R2-R9): Added a description for the action and introduced a new `token` input for GitHub authentication. Updated the `docker/bake-action` version to `v6.8.0`, added support for …
> ci: :package: push frontend assets bundle to ghcr as an supply chain artifact
