.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CODE_OF_CONDUCT.md, LICENSE, src/Application.php, src/Command/ConsoleCommand.php, src/Console/Installer.php, src/Controller/AppController.php, src/Controller/ErrorController.php, src/View/AjaxView.php, src/View/AppView.php
There's a few things that likely need a second set of eyes before they get merged in things like:
* Code of Conduct (@kfitz / @sattler9 )
* Contribution guidelines (@Sruthin86 )
* License (@kfitz )
I went with GPLv3 for the license for a couple of reasons.  Manifold is GPLv3 and they're also a Mellon funded project, so why not join the party.  Also, if we were to go with MIT, we wouldn't be able to use GPLv3 libraries (like-license restrictions in the GPL and all).
=> Updates to issue templates and all that exciting stuff

README.md
This PR:
1. Uses correct numbering for the ordered list
2. Adds a helpful tip pertaining to updating the hosts file
=> feat: Add helpful tip to README

.github/workflows/test-php.yml, client/yarn.lock, containers/phpfpm/Dockerfile
Upgrades node-forge and ini (as well as others) to clear vulnerability alerts
=> Fix dependbot alerts 

client/src/apollo/apollo-client-config.js
=> fix: remove hostname from graphql api config

docs/guide/README.md
This pull request is for testing purposes as outlined here: https://github.com/MESH-Research/CCR/issues/51
=> docs: testing documentation updates

backend/app/Models/User.php, backend/graphql/schema.graphql
Add GraphQL schema for user creation
=> feat: add user creation api

backend/composer.json, backend/composer.lock, backend/config/lighthouse.php
Upgrades lighthouse to version 5.1.  Only one minor change has been identified in our code base and `artisan test` completes successfully.
=> feat: upgrade lighthouse to version 5.1

backend/app/Models/Permission.php, backend/app/Models/Role.php, backend/app/Models/User.php, backend/composer.json, backend/composer.lock, backend/config/app.php, backend/config/permission.php, backend/database/factories/PermissionFactory.php, backend/database/factories/RoleFactory.php, backend/database/migrations/2021_01_25_163043_create_permission_tables.php, backend/tests/Feature/UserPermissionsTest.php
This PR
* Installs the third-party dependency `spatie/laravel-permissions`
* Adds `Role` and `Permission` models
* Adds some unit tests to ensure it works as expected
**Acceptance Testing**
* In the command line, navigate to the root directory of the locally cloned CCR project
* Checkout this branch `laravel-permission` in git
* Run `lando rebuild` to ensure the new dependency is installed
* Navigate to the `backend` directory
* Run tests with `lando artisan test --testsuite=Feature --filter=UserPermissionsTest`
=> build: Install Laravel permissions

client/src/layouts/App.vue, client/src/router/routes.js
Removes call to vuex store (we're no longer using vuex for state management).  Also checked the rest of the codebase and wasn't able to find any other calls to vuex remaining.
See connected issue #139  for review/acceptance criteria
=> fix: resolve console error on page load

.github/ISSUE_TEMPLATE/user_story.md
See #140 
Note, this will not be active as the new issue template until merged to master.
=> chore: update issue template

client/yarn.lock
See https://github.com/advisories/GHSA-r9p9-mrjm-926w
=> fix(client,deps): upgrade dependencies to address elliptic CVE

client/src/components/AppHeader.vue, client/src/components/atoms/EmailVerificationSendButton.vue, client/src/components/molecules/EmailVerificationBanner.vue, client/src/css/app.sass, client/src/css/quasar.variables.sass, client/src/layouts/MainLayout.vue, client/src/pages/Account/AccountLayout.vue, client/src/pages/Account/Profile.vue, client/src/pages/Admin/UsersIndex.vue, client/src/pages/Dashboard.vue, client/src/pages/Index.vue, client/src/pages/Login.vue, client/src/pages/Register.vue, client/test/cypress/integration/account.spec.js, client/test/cypress/integration/admin/users.spec.js, client/test/cypress/integration/dashboard.spec.js, client/test/cypress/integration/header.spec.js, client/test/cypress/integration/home.spec.js, client/test/cypress/integration/login.spec.js, client/test/cypress/integration/register.spec.js
This PR resolves all outstanding accessibility issues as reported by Cypress axe-core and the Chrome Extension axe DevTools for the following specs:
* Home Page `home.spec.js`
* Login Page `login.spec.js`
* Register Page `register.spec.js`
* My Dashboard Page `dashboard.spec.js`
* Account Profile Page `account.spec.js`
* Users Page `admin/users.spec.js`
Closes Issue #180
=> fix: resolve outstanding accessibility issues

docs/yarn.lock
Update dependencies for docs folder.
=> build(docs): update dependencies for vuepress

backend/composer.lock
Update backend composer dependencies
=> build(deps,backend): update backend dependencies

client/yarn.lock
Upgrade yarn dependencies on client
=> build(deps,client): update yarn dependencies

yarn.lock
Upgrade repo yarn dependencies
=> build(deps,ci): upgrade yarn dependencies

backend/app/GraphQL/Validators/ProfileMetadataAcademicProfilesValidator.php, backend/app/GraphQL/Validators/ProfileMetadataSocialMediaValidator.php, backend/app/GraphQL/Validators/ProfileMetadataValidator.php, backend/graphql/academic_profiles.graphql, backend/graphql/mailing_address.graphql, backend/graphql/profile_metadata.graphql, backend/graphql/schema.graphql, backend/graphql/social_media.graphql, backend/tests/Feature/UpdateUserMutationTest.php, backend/tests/Feature/UserQueryTest.php
Rearrange metadata fields as outlined in #203
=> refactor: rearrange profile metadata fields

backend/app/GraphQL/Validators/ProfileMetadataAcademicProfilesValidator.php, backend/graphql/academic_profiles.graphql, backend/graphql/schema.graphql, backend/tests/Feature/UserQueryTest.php
=> fix: Typo "orchid" to "orcid"

package.json
=> feat: Add script to run all tests synchronously

docs/.vuepress/config.js, docs/contributing/testing.md
This PR: 
* Increases auto-generated sidebar navigation depth to better represent document structure
* Adds a "Testing" section for the missing documentation of the [recently added](https://github.com/MESH-Research/CCR/pull/276/files) "test" command
* Re-orders unit test sections to better reflect team workflow
* Adds some language to unit test sections to improve clarity
* Fixes typos
**Review Checklist**
(from Issue #287)
-  Documentation added/changed is readable
-  Documentation added/changed is error free
-  Documentation added/changed is understandable from the perspective of someone unfamiliar with the project
Closes #287
=> docs: Document "test" Command

client/package.json, client/yarn.lock, docs/yarn.lock
- I created this branch from `development` named after the issue (#304)  `issue304-dependabot-javascript`
- merged the following pull requests
- 277
- 279
- 284
- 288
- 293
- 294
- 295
- 296
- 302
- 305
- 306
- all tests passed (Grant's `testCCR` script)
=> build(deps,client): Issue304 dependabot javascript

backend/composer.lock, composer.lock
Processed and tested all dependabot PHP requests. All tests passed on local machine.
=> build(deps): Issue316 dependabot php

client/package.json, client/src/pages/Admin/Publications.vue, client/src/pages/Login.vue, client/src/pages/Register.vue, client/src/pages/Submissions.vue, client/yarn.lock
=> build(client): update vuelidate

client/package.json, client/yarn.lock
=> revert: Revert "build(deps): bump quasar from 1.15.15 to 2.0.2 in /client"

.github/workflows/combine.yml
=> ci: update combine workflow to address vulnerability

client/src/components/atoms/UserListBasicItem.vue, client/src/components/molecules/UserListBasic.vue, client/src/pages/Admin/UsersIndex.jest.spec.js, client/src/pages/Admin/UsersIndex.vue, client/test/cypress/integration/admin/users.spec.js
User Index page now uses the components to populate the list. These components can be used for all basic user lists in the application.
closes #557
=> refactor: User Index pages and tests to use the components

.github/dependabot.yml
Ignore chalk major version updates
=> fix: joshia/dependabot modify config to ignore chalk major version change

backend/composer.json, backend/composer.lock, composer.json
This updates the config file to allow for plugins to be executed by:
* dealerdirect/phpcodesniffer-composer-installer
* composer/package-versions-deprecated
Resolves the upgrade for `Dependabot/composer/backend/development/laravel/framework 8.77.1`
=> build: Add Missing Build Configuration

client/src/App.vue, client/src/components/atoms/NotificationListItem.vue
Fix an error where DefaultLocale was set multiple times.
=> fix(client): fix time ago library error

docs/yarn.lock
This PR updates all of the doc site dependencies to  clear dependabot updtes on docs site.
=> build(docs): update all vuepress dependencies 

backend/app/GraphQL/Mutations/IntegrationTesting.php, backend/app/GraphQL/Mutations/Login.php, backend/app/GraphQL/Mutations/Logout.php, backend/composer.lock
Update all backend dependencies to clear dependabot backlog
=> build(deps,backend): update backend php dependencies

client/yarn.lock
Update client dependencies to clear up some dependabot backlogs
=> build(client,deps): update client dependencies

composer.lock, yarn.lock
Clear out some of the dependabot backlog by updating root composer and yarn packages.
=> build(deps): update root composer and yarn dependencies

client/src/components/forms/ProfileMetadataForm.vue, client/src/components/molecules/EditableList.vue, client/src/components/molecules/TagList.vue, client/test/cypress/integration/profile.spec.js
=> test(e2e): fix failing tests on nested custom components

client/src/use/user.js
FIxes mixed case email not being forced to lowercase before login.
=> test(e2e): fix failing register test

.github/workflows/auto-merge.yml
Automatically merge dependabot PRs for semver:minor upgrades, providing all tests pass.
=> build(deps): Add automerge action for semver:minor PRs

client/src/i18n/en-US/index.js, client/src/pages/Account/ProfilePage.vue, client/src/pages/Admin/PublicationDetails.jest.spec.js, client/src/pages/Admin/PublicationDetails.vue, client/src/pages/Admin/Publications.jest.spec.js, client/src/pages/Admin/PublicationsPage.vue, client/src/pages/SubmissionDetails.vue, client/src/pages/SubmissionPage.vue, client/src/use/guiElements.js
=> refactor(client): factor out repeated makeNotify functions

backend/database/seeders/PublicationSeeder.php
=> test(api): add style criteria to publication seeders

client/src/components/dialogs/BypassStyleCriteriaDialog.vue, client/src/css/app.sass, client/src/i18n/en-US/index.js, docs/index.md
Update the references in the code base to FPR to now reference CCR as requested
Closes #1029
=> fix(client,docs): Update FPR references to CCR

backend/database/seeders/DatabaseSeeder.php, backend/database/seeders/InlineCommentSeeder.php, client/src/components/atoms/InlineComment.vue, client/src/components/atoms/SubmissionContent.jest.spec.js, client/src/components/atoms/SubmissionContent.vue, client/src/components/molecules/InlineComments.vue, client/src/graphql/queries.js, client/src/tiptap/AnnotationPlugin.js, client/src/tiptap/annotation-extension.js, client/test/cypress/integration/submissionreview.spec.js, client/test/cypress/support/commands.js
Closes #1163
test(api): seed inline comments with constant data
feat(client): load content for submission review page from database
=> feat(client): display inline comment highlights on submission review page

client/src/components/AppHeader.vue, client/src/layouts/MainLayout.vue, client/test/cypress/integration/header.spec.js, client/test/cypress/integration/submissionreview.spec.js
This PR removes the application level drawer/sidebar and moves its navigation elements into a header nav.
=> feat(client): change application sidebar into header

client/src/components/AppFooter.vue
=> fix(client): make version display less verbose with tooltip

client/src/layouts/Account/AccountLayout.vue
This PR fixes should fix the majority of existing cypress issues.  I think there still may be some issues in individual local devs that we still needs to track down, but this did pass everything locally for me.
=> fix(client): Fix bug preventing user account pages from loading

client/src/components/molecules/NotificationPopup.vue, client/src/css/app.sass
Closes #1587 
- Changed background of unread notifications to blu-highlight to fix the contrast issue
=> fix: Fix color contrast unread notifications

client/quasar.conf.js, client/src/components/AppBanner.vue, client/src/components/AppHeader.vue, client/src/i18n/en-US.json, docs/contributing/README.md
* Add envs to display a banner for staging servers
* Update docs for multiple staging servers.
=> feat(client): add env vars to display an app banner

backend/app/GraphQL/Mutations/ResetPassword.php, backend/app/GraphQL/Validators/ResetPasswordInputValidator.php, backend/app/Models/User.php, backend/graphql/schema.graphql, backend/routes/web.php, client/src/components/AppHeader.vue, client/src/css/app.sass, client/src/graphql/mutations.js, client/src/i18n/en-US.json, client/src/pages/LoginPage.vue, client/src/pages/RequestPasswordReset.vue, client/src/pages/ResetPassword.vue, client/src/router/routes.js
* Adds password resetting functionality
* `/request-password-reset` for requesting password resets
* `/reset-password:token?email` as the emailed link for setting new passwords
* Fixes the appearance of the password strength "Password Analysis" section on dark mode
Closes #21
=> feat: Add Password Resetting

backend/app/GraphQL/Validators/ProfileMetadataValidator.php, backend/graphql/profile_metadata.graphql, backend/graphql/schema.graphql, backend/tests/Api/UserQueryTest.php, client/src/components/forms/ProfileMetadataForm.jest.spec.js, client/src/components/forms/ProfileMetadataForm.vue, client/src/graphql/fragments.js, client/src/graphql/mutations.js, client/src/i18n/en-US.json, client/src/pages/Account/MetadataPage.jest.spec.js, client/src/use/profileMetadata.js
This removes the "Disinterest Keywords" feature from the application.
Closes #1774
=> feat: Remove Disinterest Keywords

.github/workflows/test-unit.yml, .lando.yml, backend/composer.json, backend/composer.lock
Update php dep to 8.1 to fix some held dependency updates
=> feat: require php 8.1

client/src/i18n/en-US.json
* Fixed a typo on the home page
=> feat: Update en-US i18n.js text

backend/Dockerfile
This PR fixes a permissions error on the backend container.
=> bug(api): fix permissions on artisan command

backend/database/seeders/UxSeeder.php
=> chore: add additional accounts for ux seeders

backend/database/seeders/SubmissionSeeder.php, client/src/components/SubmissionDraftTodoItem.vue, client/src/css/app.sass, client/src/i18n/en-US.json, client/src/pages/SubmissionContent.vue, client/src/pages/SubmissionDraft.vue, client/src/pages/SubmissionReview.vue, client/test/cypress/integration/submissionreview.cy.js
This prevents submissions without content from being submitted for review
Bonus:
* Improves the appearance of the radio button options on the Submission Content page.
* Fixes some framework-created title font-sizes appearing as less than 16px
Closes #1852
=> fix: Require content for submissions

client/src/i18n/en-US.json, client/src/pages/LogoutPage.vue
This improves the positioning of the log out message and moves the text so that it is sourced from i18n.js.
Closes #1904
=> feat: Improve log out message

backend/config/purifier.php, client/src/pages/SubmissionContent.vue
Based on a request from @schopie1.  I didn't see a particular reason to not enable headings, so opening the pull request for others to weigh in or approve.
=> feat: enable headings inside submission text

client/src/pages/VerifyEmail.vue
=> fix: Make Dashboard button work on the email verification page

README.md
This fixes some URLs and the text of links within the README.
=> fix: Correct links in README.md

client/src/i18n/en-US.json
=> fix: Update en-US.json

backend/app/Models/StyleCriteria.php, backend/database/factories/StyleCriteriaFactory.php, backend/tests/Feature/StyleCriteriaTest.php, client/src/components/forms/StyleCriteriaForm.vitest.spec.js, client/src/components/forms/StyleCriteriaForm.vue, client/src/i18n/en-US.json
This increases the maximum character limit for style criteria names from 20 to 50. 
Closes #2069
=> feat: Increase character length for style criteria

docs/.vitepress/config.mts, docs/guide/contact.md, docs/guide/index.md, docs/guide/notifications.md, docs/guide/reviewing.md, docs/index.md
This restores the Guide section of the documentation site with our team's first real initiative on this material.
=> docs: Add User Guide

.editorconfig, .github/actions/build-image/action.yaml, .github/workflows/CI-helm.yaml, .github/workflows/CI.yml, .github/workflows/publish-docker.yaml, .github/workflows/publish-helm.yaml, .github/workflows/release-please.yml, backend/Dockerfile, docker-bake.hcl, release-please-config.json
** THIS SUMMARY IS GENERATED BY GITHUB COPILOT **
This pull request introduces several changes to CI/CD workflows, Docker configurations, and Helm chart management to streamline build processes, improve compatibility, and enhance deployment capabilities. The most notable updates include the addition of new workflows for publishing Docker images and Helm charts, modifications to existing workflows for better organization, and adjustments to Docker configurations to support multiple architectures.
* [`.github/workflows/CI.yml`](diffhunk://#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8R4-L30): Removed the `publish` and `deployments` jobs, added `paths-ignore` for specific files, and updated the `actions/checkout` version to v4 with additional parameters for fetching …
=> chore: update CI workflows and Docker configurations for improved build and release process
